-- MySQL Script generated by MySQL Workbench
-- Fri Apr 25 20:12:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema habcti
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema habcti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  "habcti"   ;

-- -----------------------------------------------------
-- Table "habcti"."agencies"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."agencies" (
  "agencyID" INT NOT NULL,
  "agencyName" VARCHAR(128) NULL DEFAULT NULL,
  "agencyType" VARCHAR(50) NULL DEFAULT NULL,
  "contactEmail" VARCHAR(128) NULL DEFAULT NULL,
  "contactPhone" VARCHAR(20) NULL DEFAULT NULL,
  "website" VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY ("agencyID"));



-- -----------------------------------------------------
-- Table "habcti"."state"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."state" (
  "stateID" INT NOT NULL,
  "stateName" VARCHAR(128) NULL DEFAULT NULL,
  "stateAbrv" VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY ("stateID"));



-- -----------------------------------------------------
-- Table "habcti"."localgov"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."localgov" (
  "localGovID" INT NOT NULL,
  "localGov" VARCHAR(128) NULL DEFAULT NULL,
  "govType" VARCHAR(50) NULL DEFAULT NULL,
  "stateID" INT NULL DEFAULT NULL,
  PRIMARY KEY ("localGovID"),
  CONSTRAINT "localgov_ibfk_1"
    FOREIGN KEY ("stateID")
    REFERENCES "habcti"."state" ("stateID"));



-- -----------------------------------------------------
-- Table "habcti"."bodiesofwater"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."bodiesofwater" (
  "bodyOfWaterID" INT NOT NULL,
  "bodyName" VARCHAR(128) NULL DEFAULT NULL,
  "bodyType" VARCHAR(50) NULL DEFAULT NULL,
  "freshOrSalt" VARCHAR(10) NULL DEFAULT NULL,
  "privateOrPublic" VARCHAR(10) NULL DEFAULT NULL,
  "drainageBasin" VARCHAR(50) NULL DEFAULT NULL,
  "stateID" INT NULL DEFAULT NULL,
  "localGovID" INT NULL DEFAULT NULL,
  PRIMARY KEY ("bodyOfWaterID"),
  CONSTRAINT "bodiesofwater_ibfk_1"
    FOREIGN KEY ("stateID")
    REFERENCES "habcti"."state" ("stateID"),
  CONSTRAINT "bodiesofwater_ibfk_2"
    FOREIGN KEY ("localGovID")
    REFERENCES "habcti"."localgov" ("localGovID"));



-- -----------------------------------------------------
-- Table "habcti"."federalregulations"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."federalregulations" (
  "federalRegulationID" INT NOT NULL,
  "regulationName" VARCHAR(128) NULL DEFAULT NULL,
  "regulationType" VARCHAR(45) NULL DEFAULT NULL,
  "lastUpdated" TIMESTAMP NULL DEFAULT NOW(),
  "regulationLink" VARCHAR(128) NULL DEFAULT NULL,
  "regulationNotes" TEXT NULL DEFAULT NULL,
  "effectiveDate" DATE NULL DEFAULT NULL,
  "agencyID" INT NULL DEFAULT NULL,
  PRIMARY KEY ("federalRegulationID"),
  CONSTRAINT "federalregulations_ibfk_1"
    FOREIGN KEY ("agencyID")
    REFERENCES "habcti"."agencies" ("agencyID"));



-- -----------------------------------------------------
-- Table "habcti"."regulations"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."regulations" (
  "regulationID" INT NOT NULL,
  "regulationName" VARCHAR(128) NULL DEFAULT NULL,
  "regulationType" VARCHAR(45) NULL DEFAULT NULL,
  "lastUpdated" TIMESTAMP NULL DEFAULT NOW(),
  "regulationLink" VARCHAR(128) NULL DEFAULT NULL,
  "regulationNotes" TEXT NULL DEFAULT NULL,
  "effectiveDate" DATE NULL DEFAULT NULL,
  "stateID" INT NULL DEFAULT NULL,
  "localGovID" INT NULL DEFAULT NULL,
  "bodyOfWaterID" INT NULL DEFAULT NULL,
  "federalRegulationID" INT NULL DEFAULT NULL,
  "agencyID" INT NULL DEFAULT NULL,
  PRIMARY KEY ("regulationID"),
  CONSTRAINT "regulations_ibfk_1"
    FOREIGN KEY ("stateID")
    REFERENCES "habcti"."state" ("stateID"),
  CONSTRAINT "regulations_ibfk_2"
    FOREIGN KEY ("localGovID")
    REFERENCES "habcti"."localgov" ("localGovID"),
  CONSTRAINT "regulations_ibfk_3"
    FOREIGN KEY ("bodyOfWaterID")
    REFERENCES "habcti"."bodiesofwater" ("bodyOfWaterID"),
  CONSTRAINT "regulations_ibfk_4"
    FOREIGN KEY ("federalRegulationID")
    REFERENCES "habcti"."federalregulations" ("federalRegulationID"),
  CONSTRAINT "regulations_ibfk_5"
    FOREIGN KEY ("agencyID")
    REFERENCES "habcti"."agencies" ("agencyID"));



-- -----------------------------------------------------
-- Table "habcti"."permits"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."permits" (
  "permitID" INT NOT NULL,
  "permitName" VARCHAR(128) NULL DEFAULT NULL,
  "validFor" DATE NULL DEFAULT NULL,
  "permitDocs" TEXT NULL DEFAULT NULL,
  "permitLink" VARCHAR(128) NULL DEFAULT NULL,
  "permitNotes" TEXT NULL DEFAULT NULL,
  "regulationID" INT NULL DEFAULT NULL,
  "federalRegulationID" INT NULL DEFAULT NULL,
  PRIMARY KEY ("permitID"),
  CONSTRAINT "permits_ibfk_1"
    FOREIGN KEY ("regulationID")
    REFERENCES "habcti"."regulations" ("regulationID"),
  CONSTRAINT "permits_ibfk_2"
    FOREIGN KEY ("federalRegulationID")
    REFERENCES "habcti"."federalregulations" ("federalRegulationID"));



-- -----------------------------------------------------
-- Table "habcti"."controlmethods"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."controlmethods" (
  "controlMethodID" INT NOT NULL,
  "controlName" VARCHAR(50) NULL DEFAULT NULL,
  "controlType" VARCHAR(50) NULL DEFAULT NULL,
  "controlCost" DECIMAL(19,4) NULL DEFAULT NULL,
  "algaeSpecies" VARCHAR(50) NULL DEFAULT NULL,
  "regulationID" INT NULL DEFAULT NULL,
  "permitID" INT NULL DEFAULT NULL,
  PRIMARY KEY ("controlMethodID"),
  CONSTRAINT "controlmethods_ibfk_1"
    FOREIGN KEY ("permitID")
    REFERENCES "habcti"."permits" ("permitID"),
  CONSTRAINT "controlmethods_ibfk_2"
    FOREIGN KEY ("regulationID")
    REFERENCES "habcti"."regulations" ("regulationID"));



-- -----------------------------------------------------
-- Table "habcti"."literature"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."literature" (
  "literatureID" INT NOT NULL,
  "literatureLink" VARCHAR(128) NULL DEFAULT NULL,
  "literatureDescription" TEXT NULL DEFAULT NULL,
  "literaturePublishDate" DATE NULL DEFAULT NULL,
  "controlMethodID" INT NULL DEFAULT NULL,
  PRIMARY KEY ("literatureID"),
  CONSTRAINT "literature_ibfk_1"
    FOREIGN KEY ("controlMethodID")
    REFERENCES "habcti"."controlmethods" ("controlMethodID"));



-- -----------------------------------------------------
-- Table "habcti"."permittags"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."permittags" (
  "permitTagID" INT NOT NULL,
  "tag" VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY ("permitTagID"));



-- -----------------------------------------------------
-- Table "habcti"."permitstags"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."permitstags" (
  "permits_permitID" INT NOT NULL,
  "permittags_tagID" INT NOT NULL,
  PRIMARY KEY ("permits_permitID", "permittags_tagID"),
  CONSTRAINT "permitstags_ibfk_1"
    FOREIGN KEY ("permits_permitID")
    REFERENCES "habcti"."permits" ("permitID"),
  CONSTRAINT "permitstags_ibfk_2"
    FOREIGN KEY ("permittags_tagID")
    REFERENCES "habcti"."permittags" ("permitTagID"));



-- -----------------------------------------------------
-- Table "habcti"."regulationtags"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."regulationtags" (
  "regulationTagID" INT NOT NULL,
  "tag" VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY ("regulationTagID"));



-- -----------------------------------------------------
-- Table "habcti"."regulationstags"
-- -----------------------------------------------------
CREATE TABLE  "habcti"."regulationstags" (
  "regulations_regulationID" INT NOT NULL,
  "regulationtags_regulationTagID" INT NOT NULL,
  PRIMARY KEY ("regulations_regulationID", "regulationtags_regulationTagID"),
  CONSTRAINT "regulationstags_ibfk_1"
    FOREIGN KEY ("regulations_regulationID")
    REFERENCES "habcti"."regulations" ("regulationID"),
  CONSTRAINT "regulationstags_ibfk_2"
    FOREIGN KEY ("regulationtags_regulationTagID")
    REFERENCES "habcti"."regulationtags" ("regulationTagID"));



